services:
  # A web service
  - type: web
    name: esgiRenderNodeExo
    runtime: node
    region: frankfurt
    plan: free
    repo: https://github.com/Dan-Popescu/esgiRenderNodeExo
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DB_CONNECTION_STRING
      fromDatabase:
        name: esgiRenderNodeExoDb
        property: connectionString

databases:
  - name: esgiRenderNodeExoDb
    region: frankfurt
